[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/tomorrow-night.toml"
]


[font]
# normal = { family = "foobar", style = "Regular" }
# bold = { family = "foobar", style = "Bold" }
# offset = { x = 0, y = 0 }
# glyph_offset = { x = 0, y = 0 }
# normal = { family = "AdwaitaMono Nerd Font", style = "Regular" }
# 
# normal = { family = "GeistMono NF", style = "Regular" }
normal = { family = "Google Sans Code NF", style = "Regular" }
# size = 11

# [[font.normal_extra]]
# family = "Noto Color Emoji"
# [[font.glyph_offset]]
# optional tuningdimensions = { columns = <integer>, lines = <integer> }

# Add this:
# [font]
#   [[font.normal]]
#   family = "AdwaitaMono Nerd Font"


# [font]
# # normal = { family = "Google Sans Code", style = "Regular" }
# normal = { family = "AdwaitaMono Nerd Font", style = "Regular" }
# glyph_offset = { x = 0, y = 0 }


[window]
dimensions = { columns = 259, lines = 60}
option_as_alt = "Both"

[cursor]
style = { blinking = "Always" }
blink_interval = 500
blink_timeout = 0



[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "exec zellij attach --create main"] }

[keyboard]
bindings = [
{ key = "v", mods = "Super", action = "Paste" },
{ key = "c", mods = "Super", chars = "Copy" },
]



