# Navigate splits/windows
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right

# Clipboard
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# Tab navigation
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab

# Splits
enabled_layouts grid
# enabled_layouts splits,stack
map ctrl+shift+o launch --type window --location vsplit
map ctrl+shift+x close_window

# Resize splits/windows
map ctrl+alt+h resize_window narrower 20
map ctrl+alt+j resize_window taller 20
map ctrl+alt+k resize_window shorter 20
map ctrl+alt+l resize_window wider 20


map ctrl+alt+v show_scrollback
