# Navigate splits/windows
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l


# Clipboard
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard


# Tab navigation
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab

# Splits
enabled_layouts splits,stack
# enabled_layouts splits,stack
map ctrl+shift+o launch --type window --location vsplit --cwd=current
map ctrl+shift+, launch --type window --location hsplit --cwd=current
map ctrl+shift+x close_window

# Resize splits/windows
map ctrl+alt+h resize_window narrower 5
map ctrl+alt+k resize_window taller 5
map ctrl+alt+j resize_window shorter 5
map ctrl+alt+l resize_window wider 5


map ctrl+shift+z toggle_layout stack
map ctrl+shift+enter toggle_layout stack

map f5 load_config_file

map ctrl+shift+e show_scrollback

