linux_display_server x11
# font_family AdwaitaMono Nerd Font Mono
# font_family CaskaydiaMono NF
font_family Google Sans Code NF
font_size 11
shell_integration enabled
allow_remote_control yes
listen_on unix:/tmp/mykitty
modify_font cell_height +3px
enable_audio_bell no


# scrollback_pager ~/dotfiles/kitty/scrollback.sh
# scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
scrollback_pager nvim --cmd 'let g:kitty_scrollback=1' --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

include keymap.conf
# include themes/catppuccin-mocha.conf
# include themes/tokyonight.conf
# include themes/material-dark-alt.conf
# include themes/solarized.conf
include themes/tomorrow-night.conf

remember_window_size  yes
initial_window_width  300
initial_window_height 90

# tab bar
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_bar_min_tabs            2
tab_bar_align               left
tab_title_template ' {index}: {" " if layout_name == "stack" else ""}{title}'
active_tab_font_style bold
# tab_bar_margin_height 0 1
# tab_bar_margin_color #444444

include kitty.local.conf
