linux_display_server x11
font_family Source Code Pro
font_size 13
shell_integration enabled
allow_remote_control yes
listen_on unix:/tmp/mykitty

# scrollback_pager ~/dotfiles/kitty/scrollback.sh
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

include keymap.conf
include tokyonight.conf

remember_window_size  yes
initial_window_width  300
initial_window_height 90


