# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch$git_commit$git_state\
$python\
$sudo\
$aws\
$kubernetes\
$terraform\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[\$](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[](bold green)'


[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 1

[git_branch]
format = "[$symbol\\($branch(:$remote_branch)\\)]($style) "
symbol = ""

[python]
format = "[${symbol} ${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"

[sudo]
format = "[$symbol] ($style)"

[cmd_duration]
format = "took [$duration]($style)"

[aws]
# format = 'on [$symbol$profile]($style)'
format = "[$symbol\\($profile\\)]($style) "
style = 'fg:208'
symbol = " "

[kubernetes]
format = "[$symbol\\($context(\\($namespace\\))\\)]($style) "
disabled = false
symbol = " "


[terraform]
format = "[$symbol\\($workspace\\)]($style) "
symbol = " "
