# Material Darker theme for Kitty Terminal
# Based on marko-cerovac/material.nvim

# Background & Foreground
background            #212121
foreground            #B0BEC5

# Cursor
cursor                #FFCC00
cursor_text_color     #212121

# Selection
selection_background  #404040
selection_foreground  #B0BEC5

# URL color
url_color             #80CBC4

# Window border colors
# active_border_color   #FF9800
# inactive_border_color #343434
active_border_color none
inactive_border_color #424242

# Tab bar
active_tab_foreground   #FF9800
active_tab_background   #212121
inactive_tab_background #1A1A1A
inactive_tab_foreground  #d8d8d8

# active_tab_foreground   #444444
# active_tab_background   #dedede
# inactive_tab_foreground #e4e4e4
# inactive_tab_background #1b1b1a

# Line numbers / dimmed text
dim_opacity 0.75

# Black (ansi 0 & 8)
color0  #424242
# color8  #212121
# color8  #515151
color8 #474747

# Red (ansi 1 & 9)
color1  #DC6068
color9  #F07178

# Green (ansi 2 & 10)
color2  #ABCF76
color10 #C3E88D

# Yellow (ansi 3 & 11)
color3  #E6B455
color11 #FFCB6B

# Blue (ansi 4 & 12)
color4  #6E98EB
color12 #82AAFF

# Magenta / Purple (ansi 5 & 13)
color5  #B480D6
color13 #C792EA

# Cyan (ansi 6 & 14)
color6  #71C6E7
color14 #89DDFF

# White (ansi 7 & 15)
color7  #EEFFFF
color15 #B0BEC5
