color0 #000000
color1 #cc6666
color2 #b5bd68
color3 #f0c674
color4 #81a2be
color5 #b294bb
color6 #8abeb7
color7 #ffffff
color8 #4c4c4c
color9 #cc6666
color10 #b5bd68
color11 #f0c674
color12 #81a2be
color13 #b294bb
color14 #8abeb7
color15 #ffffff
background #1d1f21
selection_foreground #1d1f21

cursor #c5c8c6
cursor_text_color #1d1f21

foreground #c5c8c6
selection_background #c5c8c6

tab_bar_background             #1d1f21

active_tab_foreground          #1d1f21
active_tab_background         #b5bd68
active_tab_font_style          bold

inactive_tab_foreground        #c5c8c6
inactive_tab_background       #1d1f21

inactive_tab_font_style        normal
